#!/bin/bash
read a; read b; read c;
if [[ "$a" -ge "$b" ]] && [[ "$a" -ge "$c" ]]; then
echo "$a"
exit 1
fi
if [[ "$b" -ge "$a" ]] && [[ "$b" -ge "$c" ]]; then
echo "$b"
exit 2
fi
if [[ "$c" -ge "$a" ]] && [[ "$c" -ge "$b" ]]; then
echo "$c"
exit 2
fi
